import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tattoo_social_app/models/enums/app_theme.dart';
import 'package:tattoo_social_app/models/enums/gender_type.dart';
import 'package:tattoo_social_app/models/enums/subscription_type.dart';
import 'package:tattoo_social_app/models/event_model.dart';
import 'package:tattoo_social_app/models/product_model.dart';

part 'current_user_data.freezed.dart';

@freezed
abstract class CurrentUserData with _$CurrentUserData {
  const factory CurrentUserData({
    String? email,
    String? username,
    String? profileImageUrl,
    String? bio,
    List<String>? specialties,
    Map<String, dynamic>? additionalInfo,
    Gender? gender,
    String? phoneNumber,
    String? postalAddress,
    String? city,
    String? country,
    String? language,
    AppTheme? theme,
    bool? isOnline,
    DateTime? lastSeen,
    DateTime? signedUpAt,
    SubscriptionType? subscriptionType,
    DateTime? subscriptionStartDate,
    DateTime? subscriptionEndDate,
    bool? isTrialPeriod,
    List<String>? postIds,
    String? portfolioUrl,
    List<EventModel>? organizedEvents,
    String? companyName,
    List<ProductModel>? products,
    String? websiteUrl,
    Map<String, String>? socialMediaLinks,
    List<String>? following,
    List<String>? followers,
    required String id, // Added the id property
  }) = _CurrentUserData;

  factory CurrentUserData.initial() => const CurrentUserData(id: '');
}

// This part will be generated by running:
// flutter pub run build_runner build --delete-conflicting-outputs
// You don't need to define this manually.
